
import { z } from 'zod';

export const contactFormSchema = z.object({
  name: z.string().min(2, { message: "Name must be at least 2 characters." }).max(50, { message: "Name cannot exceed 50 characters." }),
  email: z.string().email({ message: "Please enter a valid email address." }),
  subject: z.string().min(5, { message: "Subject must be at least 5 characters." }).max(100, { message: "Subject cannot exceed 100 characters." }),
  message: z.string().min(10, { message: "Message must be at least 10 characters." }).max(1000, { message: "Message cannot exceed 1000 characters." }),
});

export type ContactFormData = z.infer<typeof contactFormSchema>;

// Schema for data as it is stored in MongoDB and/or retrieved for client-side display
// _id is typically a string representation of MongoDB's ObjectId when fetched
export const contactMessageSchema = contactFormSchema.extend({
    _id: z.string(), // Represents ObjectId as string
    createdAt: z.date(),
});

export type ContactMessage = z.infer<typeof contactMessageSchema>;

// Schema for data to be inserted into MongoDB (server-side)
// Excludes _id as it's auto-generated by MongoDB
export const contactMessageToInsertSchema = contactFormSchema.extend({
    createdAt: z.date(),
});

export type ContactMessageToInsert = z.infer<typeof contactMessageToInsertSchema>;
